### PR TITLE
Multi line examples scenarios

### PR DESCRIPTION
**Pull request by thr0w**
In some cases we need examples with linefeed char, I changed yadda to support examples with multiline. Just leave a blank before each example to use multi line mode.

I've created new tests for multiline mode, all tests passing.
I also add option use  `┆ (\u2506)` column char separator.
Readme was changed to explain new features.

```
Scenario: [case] Scenario

    Given I need to transpile [case]
    When EcmaScript6=[EcmaScript6]
    Then EcmaScript5=[EcmaScript5]

Examples:
  case             | EcmaScript6              | EcmaScript5

  arrow function   | var r=arr.map((x)=>x*x); | "use strict";
                   |                          |
                   |                          | var r = arr.map(function (x) {
                   |                          |   return x * x;
                   |                          | });

  template strings | var s=`x=${x}            | "use strict";
                   | y=${y}`;                 |
                   |                          | var s = "x=" + x + "\ny=" + y;

```

> complete example at examples/multiline-examples

### CODE REVIEW

**Comment by cressie176** [comment]
Thats really cool. Quite likely that I won't be able to merge for around a week but will get to it after that. Thanks

**Comment by ami44** [comment]
excellent !
:+1:

**Comment by thr0w** [comment]
New features: Typed columns and annotations for each example

Typed columns: used when we need some feature for each column, I made two:
* ID: when a column is identifier and can't be duplicated
* LOC: when it's important know column position (line/column) on feature file. As we are parsing column data using something like babel.

> sample of typed columns: [https://github.com/thr0w/yadda/blob/master/test/features/multiline_example_with_typed_columns.feature]

> sample of annotated examples: [https://github.com/thr0w/yadda/blob/master/test/features/example_scenarios_with_annotations.feature]

I made tests for new features.

**Comment by ami44** [comment]
Empty line separator is not easy see separation
Is it possible to have more readable example like this :
(or as an option)
```
Scenario: [case] Scenario

    Given I need to transpile [case]
    When EcmaScript6=[EcmaScript6]
    Then EcmaScript5=[EcmaScript5]

Examples:
  case             | EcmaScript6              | EcmaScript5
  --------------------------------------------------------------------------------------------------------------
  arrow function   | var r=arr.map((x)=>x*x); | "use strict";
                   |                          |
                   |                          | var r = arr.map(function (x) {
                   |                          |   return x * x;
                   |                          | });
  --------------------------------------------------------------------------------------------------------------
  template strings | var s=`x=${x}            | "use strict";
                   | y=${y}`;                 |
                   |                          | var s = "x=" + x + "\ny=" + y;
  --------------------------------------------------------------------------------------------------------------
```

Ami44

**Comment by thr0w** [comment]
Yes @ami44, it's better. Thanks!

**Comment by thr0w** [comment]
Guys, thanks for yadda, it was encouraging me a in project that transpile async/await to callbacks.
https://github.com/thr0w/asynccbn  :)

If I can help you with something, please tell me:

**Comment by cressie176** [comment]
Been away for the last few days, but like the changes. Will review / pull ASAP. Thanks for contributing

**Comment by cressie176** [comment]
Still working through. One issue I've come across is that indentation breaks for the first column because the TEXT_REGEX gobbles up all leading whitespace. In hindsight this was a bad assumption so I'll explicitly ltrim in all the text handlers, except for multiline examples, which I'll ltrim based on the position of the first header as per the other columns

**Comment by thr0w** [comment]
other alternative can be delegate to the specification how match text lines.
`if (match = specification.TEXT_REGEX.exec(line)) return specification.handle('Text', match[1]);`

But still important share current line number

**Comment by cressie176** [comment]
I've updated Yadda (master) with everything except the typed columns. I like the idea, but don't think it should be baked into the parser. ID and LOC are quite specific to your scenario so I'd prefer to implement via a plugin mechanism.

I've run it against your tests in https://github.com/thr0w/asynccbn and they pass once I flattend es5 and es7 variables and replaced the blank lines with dashes. I also had to move the @Pending annotations into the row rather than above it.

Let me know what you think. Thanks again for your contribution.

S

**Comment by cressie176** [comment]
I've added dictionary converters which can be used as an alternative to typed columns. They work with both normal steps and steps generated from examples. I've also updated the mutliline example with a "unique" converter for reference. See [here](https://github.com/acuminous/yadda/blob/master/examples/multiline-examples/transpile-library.js#L16)

**Comment by cressie176** [comment]
Added support for the following example table meta fields.

\<field>.index
\<field>.start.line
\<field>.start.column

Didn't see the purpose of \<field>.end.line and \<field>.end.column but if you have one, I don't object to including them. I think this implements everything in this PR. Thanks again for your efforts.

**Comment by thr0w** [comment]
Nice job men! Thank you!

**Pull request closed without merging**
