### PR TITLE
Karma support

### PR DESCRIPTION
**Pull request by inf3rno**
Added Karma support with Browserify. #58
Removed env variables from npm scripts. #198

### CODE REVIEW

**Comment by inf3rno** [comment]
Hmm, the code is not perfect, is there a way to modify it? The `fs.workingDirectory` and the `process.cwd()` is currently `"."` instead of `"/"`. Otherwise it works with browserify. I don't know whether it works with webpack. It requires a `path` module and creates an `fs` shim. Browserify has a built-in emulated `path` module.

**Comment by inf3rno** [comment]
Can you refuse this and give some information about jslint and probably phantomjs? Is there a way to run phantomjs tests? I mean I found a phantomjs shim and a casper plugin, which are not tested as far as I can tell. We need automated tests for those environments as well to test whether the phantomjs fs shim works. I don't know who wrote that, but he forgot to write tests.

**Comment by inf3rno** [comment]
I removed the fork and I'll apply the changes again and send the pull request later. I did not manage to amend the last commit, somehow I got merge conflicts with remote/origin, probably because the latest commit was already pushed.

**Comment by cressie176** [comment]
Re casper plugin and phantom shim, there are no unit tests for these, but I run the examples before pushing.

**Comment by inf3rno** [comment]
How did you run them?

**Comment by cressie176** [comment]
Probably from package.jso npm run examples. They can be run individually too

On Friday, 11 March 2016, Jánszky László Lajos <notifications@github.com>
wrote:

> How did you run them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acuminous/yadda/pull/199#issuecomment-195522589>.
>


-- 
http://peaceoneday.org/

**Comment by inf3rno** [comment]
@cressie176 Yes, I found it now, there is a casper example. Some of the tests does not run properly on Windows, I guess some of the dependencies are not Windows compatible, I did not check. What do you suggest by karma? I already added integration tests for fs, path and process, so for the shims and I think by tradition it would be much better to run integration tests on these platform than putting basic usage into examples. This integration tests could be run only by travis e.g.

```
script:
  - npm run test && npm run karma && npm run phantomjs
```

just to be certain, that the lib works properly on every platform, and by development we could use only node tests `npm run test`. Is this okay? What do you think?

**Comment by inf3rno** [comment]
@cressie176 
I sent the request again with the enhanced code. I left out the phantomjs part for now.
It would be probably beneficial to create a chat room for Yadda discussions here: https://gitter.im , so we would not need to use the issue tracker for discussions, questions, etc...

**Comment by cressie176** [comment]
Good idea re gitter. Done.

**Pull request closed without merging**
